"""Update users,tints,bookings tables

Revision ID: 0467d94410db
Revises: e2c7dfd25326
Create Date: 2026-05-31 22:04:56.143047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0467d94410db'
down_revision: Union[str, Sequence[str], None] = 'e2c7dfd25326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_reference', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_reason', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('booking_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'tint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.add_column('tints', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('tints', sa.Column('film_brand', sa.String(), nullable=False))
    op.add_column('tints', sa.Column('film_series', sa.String(), nullable=True))
    op.add_column('tints', sa.Column('tint_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('tints', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('tints', sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tints', sa.Column('warranty_months', sa.Integer(), nullable=True))
    op.add_column('tints', sa.Column('warranty_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tints', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('tints', sa.Column('compliance_status', sa.String(), nullable=True))
    op.alter_column('tints', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tints', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'tints', 'users', ['approved_by'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'tints', type_='foreignkey')
    op.alter_column('tints', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tints', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tints', 'compliance_status')
    op.drop_column('tints', 'notes')
    op.drop_column('tints', 'warranty_expiry')
    op.drop_column('tints', 'warranty_months')
    op.drop_column('tints', 'installation_date')
    op.drop_column('tints', 'currency')
    op.drop_column('tints', 'tint_config')
    op.drop_column('tints', 'film_series')
    op.drop_column('tints', 'film_brand')
    op.drop_column('tints', 'approved_by')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.alter_column('bookings', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'tint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'booking_metadata')
    op.drop_column('bookings', 'cancellation_reason')
    op.drop_column('bookings', 'currency')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'installation_date')
    op.drop_column('bookings', 'booking_reference')
    # ### end Alembic commands ###
