"""fix_tint_table_schema

Revision ID: 0d5a178ae23c
Revises: 8621d27a9e5b
Create Date: 2026-05-31 23:00:38.740502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5a178ae23c'
down_revision: Union[str, Sequence[str], None] = '8621d27a9e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tints', 'tint_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tints', 'tint_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
