"""update_vehicle_table

Revision ID: 8621d27a9e5b
Revises: 29d699887545
Create Date: 2026-05-31 22:29:04.819071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8621d27a9e5b'
down_revision: Union[str, Sequence[str], None] = '29d699887545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vin', sa.String(length=17), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=20), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(length=20), nullable=True))
    op.add_column('vehicles', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('vehicles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'vehicles', ['vin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.alter_column('vehicles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'is_active')
    op.drop_column('vehicles', 'features')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'vin')
    # ### end Alembic commands ###
